export const cards = [
  {
    id: 1,
    image: '/public/image/Nuxt.png',
    name: 'AppWorkWeb1.workName',
    description: 'AppWorkWeb1.workDescription',
    stack: 'AppWorkWeb1.workStack',
    tools: ['HTML', 'CSS', 'Nuxt 3'],
    urlGit: 'https://github.com/JED-Studio/Statut_Nuxt',
    urlWeb: 'https://jed-studio.github.io/Statut_Nuxt/',
    cardId: 1,
  },
  {
    id: 2,
    image: '/public/image/Image (152).jpg',
    name: 'AppWorkWeb2.workName',
    description: 'AppWorkWeb2.workDescription',
    stack: 'AppWorkWeb2.workStack',
    tools: ['HTML', 'CSS', 'JS'],
    urlGit: 'https://github.com/JED-Studio/Test-task',
    urlWeb: 'https://jed-studio.github.io/Test-task/',
    cardId: 1,
  },
  {
    id: 3,
    image: '/public/image/Image (155).jpg',
    name: 'AppWorkWeb3.workName',
    description: 'AppWorkWeb3.workDescription',
    stack: 'AppWorkWeb3.workStack',
    tools: ['HTML', 'CSS', 'JS'],
    urlGit: 'https://github.com/JED-Studio/3d_jed',
    urlWeb: 'https://jed-studio.github.io/3d_jed/',
    cardId: 1,
  },
  {
    id: 4,
    image: '/public/image/Image (164).jpg',
    name: 'AppWorkWeb4.workName',
    description: 'AppWorkWeb4.workDescription',
    stack: 'AppWorkWeb4.workStack',
    tools: ['HTML', 'CSS', 'JS'],
    urlGit: 'https://zabitov-tour05.ru/#section_answers',
    urlWeb: 'https://zabitov-tour05.ru/#section_answers',
    cardId: 1,
  },
  {
    id: 5,
    image: '/public/image/JavaS.png',
    name: 'AppWorkJs1.workName',
    description: 'AppWorkJs1.workDescription',
    stack: 'AppWorkJs1.workStack',
    tools: ['HTML', 'CSS', 'Vue 3', 'Vi18n', 'Tailwind'],
    urlGit: 'https://github.com/JED-Studio/Quiz',
    urlWeb: 'https://github.com/JED-Studio/Quiz',
    cardId: 2,
  },
  {
    id: 6,
    image: '/public/image/Scrin.png',
    name: 'AppWorkJs2.workName',
    description: 'AppWorkJs2.workDescription',
    stack: 'AppWorkJs2.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    urlGit: 'https://github.com/JED-Studio/To-do-list__O2',
    urlWeb: 'https://jed-studio.github.io/To-do-list__O2/',
    cardId: 2,
  },
  {
    id: 7,
    image: '/public/image/Image (121).png',
    name: 'AppWorkJs3.workName',
    description: 'AppWorkJs3.workDescription',
    stack: 'AppWorkJs3.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    urlGit: 'https://github.com/JED-Studio/Qpick',
    urlWeb: ' https://jed-studio.github.io/Qpick/',
    cardId: 2,
  },
  {
    id: 8,
    image: '/public/image/Image (154).jpg',
    name: 'AppWorkJs4.workName',
    description: 'AppWorkJs4.workDescription',
    stack: 'AppWorkJs4.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    urlGit: 'https://github.com/JED-Studio/Salvator/tree/main/Alvator',
    urlWeb: 'https://github.com/JED-Studio/Salvator/tree/main/Alvator',
    cardId: 2,
  },
  {
    id: 9,
    image: '/public/image/Image (120).png',
    name: 'AppWorkJs5.workName',
    description: 'AppWorkJs5.workDescription',
    stack: 'AppWorkJs5.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    urlGit: 'https://github.com/JED-Studio/To-do-list/tree/main/ToDoList2.0/Todo',
    urlWeb: 'https://github.com/JED-Studio/To-do-list/tree/main/ToDoList2.0/Todo',
    cardId: 2,
  },
]
