export const cards = [
  {
    image: '/public/image/Nuxt.png',
    name: 'AppWorkWeb1.workName',
    description: 'AppWorkWeb1.workDescription',
    stack: 'AppWorkWeb1.workStack',
    tools: ['HTML', 'CSS', 'Nuxt 3'],
    urlGit: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    urlWeb: '',
    cardId: 1,
  },
  {
    image: '/public/image/Image (152).jpg',
    name: 'AppWorkWeb2.workName',
    description: 'AppWorkWeb2.workDescription',
    stack: 'AppWorkWeb2.workStack',
    tools: ['HTML', 'CSS', 'JS'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 1,
  },
  {
    image: '/public/image/Image (155).jpg',
    name: 'AppWorkWeb3.workName',
    description: 'AppWorkWeb3.workDescription',
    stack: 'AppWorkWeb3.workStack',
    tools: ['HTML', 'CSS', 'JS'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 1,
  },
  {
    image: '/public/image/Image (164).jpg',
    name: 'AppWorkWeb4.workName',
    description: 'AppWorkWeb4.workDescription',
    stack: 'AppWorkWeb4.workStack',
    tools: ['HTML', 'CSS', 'JS'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 1,
  },
  {
    image: '/public/image/JavaS.png',
    name: 'AppWorkJs1.workName',
    description: 'AppWorkJs1.workDescription',
    stack: 'AppWorkJs1.workStack',
    tools: ['HTML', 'CSS', 'Vue 3', 'Vi18n', 'Tailwind'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 2,
  },
  {
    image: '/public/image/Scrin.png',
    name: 'AppWorkJs2.workName',
    description: 'AppWorkJs2.workDescription',
    stack: 'AppWorkJs2.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 2,
  },
  {
    image: '/public/image/Image (121).png',
    name: 'AppWorkJs3.workName',
    description: 'AppWorkJs3.workDescription',
    stack: 'AppWorkJs3.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 2,
  },
  {
    image: '/public/image/Image (154).jpg',
    name: 'AppWorkJs4.workName',
    description: 'AppWorkJs4.workDescription',
    stack: 'AppWorkJs4.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 2,
  },
  {
    image: '/public/image/Image (120).png',
    name: 'AppWorkJs5.workName',
    description: 'AppWorkJs5.workDescription',
    stack: 'AppWorkJs5.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 2,
  },
]
