export const cards = [
  {
    title: 'AppWorkWeb1.workFinalized',
    image: '/public/image/Nuxt.png',
    name: 'AppWorkWeb1.workName',
    description: 'AppWorkWeb1.workDescription',
    stack: 'AppWorkWeb1.workStack',
    tools: ['HTML', 'CSS', 'Nuxt 3'],
    urlGit: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    urlWeb: '',
    cardId: 1,
  },
  {
    title: 'AppWorkWeb2.workFinalized',
    image: '/public/image/Image (152).jpg',
    name: 'AppWorkWeb2.workName',
    description: 'AppWorkWeb2.workDescription',
    stack: 'AppWorkWeb2.workStack',
    tools: ['HTML', 'CSS', 'JS'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 1,
  },
  {
    title: 'AppWorkWeb3.workFinalized',
    image: '/public/image/Image (155).jpg',
    name: 'AppWorkWeb3.workName',
    description: 'AppWorkWeb3.workDescription',
    stack: 'AppWorkWeb3.workStack',
    tools: ['HTML', 'CSS', 'JS'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 1,
  },
  {
    title: 'AppWorkJs1.workFinalized',
    image: '/public/image/JavaS.png',
    name: 'AppWorkJs1.workName',
    description: 'AppWorkJs1.workDescription',
    stack: 'AppWorkJs1.workStack',
    tools: ['HTML', 'CSS', 'Vue 3', 'Vi18n', 'Tailwind'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 2,
  },
  {
    title: 'AppWorkJs2.workFinalized',
    image: '/public/image/Scrin.png',
    name: 'AppWorkJs2.workName',
    description: 'AppWorkJs2.workDescription',
    stack: 'AppWorkJs2.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 2,
  },
  {
    title: 'AppWorkJs2.workFinalized',
    image: '/public/image/Scrin.png',
    name: 'AppWorkJs2.workName',
    description: 'AppWorkJs2.workDescription',
    stack: 'AppWorkJs2.workStack',
    tools: ['HTML', 'CSS', 'Vue 3'],
    url: 'https://github.com/Flowseal/zapret-discord-youtube/releases',
    cardId: 2,
  },
]
